-- Users table seeds here (Example)
INSERT INTO users (name, email, password) VALUES ('Alice', 'alice@yahoo,ca','password');
INSERT INTO users (name, email, password) VALUES ('Kira','kira@yahoo,ca','password');
INSERT INTO users (name, email, password) VALUES ('Bob', 'bob@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('John', 'john@hotmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Emma', 'emma@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Michael', 'michael@yahoo.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Sophia', 'sophia@hotmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Daniel', 'daniel@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Olivia', 'olivia@yahoo.com', 'password');
INSERT INTO users (name, email, password) VALUES ('William', 'william@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Ava', 'ava@hotmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Alexander', 'alexander@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Mia', 'mia@yahoo.com', 'password');
INSERT INTO users (name, email, password) VALUES ('James', 'james@hotmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Charlotte', 'charlotte@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Benjamin', 'benjamin@yahoo.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Amelia', 'amelia@hotmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Elijah', 'elijah@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Abigail', 'abigail@yahoo.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Ryan', 'ryan@hotmail.com', 'password');
