INSERT INTO options (question_id, description) VALUES (1, 'Hong Kong');
INSERT INTO options (question_id, description) VALUES (1, 'Canada');
INSERT INTO options (question_id, description) VALUES (1, 'Germany');
INSERT INTO options (question_id, description) VALUES (1, 'Dubai');
INSERT INTO options (question_id, description) VALUES (2, 'Italian');
INSERT INTO options (question_id, description) VALUES (2, 'English');
INSERT INTO options (question_id, description) VALUES (2, 'Spanish');
INSERT INTO options (question_id, description) VALUES (2, 'Mandarin');
INSERT INTO options (question_id, description) VALUES (3, 'Smith');
INSERT INTO options (question_id, description) VALUES (3, 'Stone');
INSERT INTO options (question_id, description) VALUES (3, 'Lawson');
INSERT INTO options (question_id, description) VALUES (3, 'Trish');
INSERT INTO options (question_id, description) VALUES (4, 'HIV');
INSERT INTO options (question_id, description) VALUES (4, 'Scurvy');
INSERT INTO options (question_id, description) VALUES (4, 'Hepatitis');
INSERT INTO options (question_id, description) VALUES (4, 'Ebola');
INSERT INTO options (question_id, description) VALUES (5, 'Apollo');
INSERT INTO options (question_id, description) VALUES (5, 'Dionysus');
INSERT INTO options (question_id, description) VALUES (5, 'Hephaestus');
INSERT INTO options (question_id, description) VALUES (5, 'Zeus');
INSERT INTO options (question_id, description) VALUES (6, '1914');
INSERT INTO options (question_id, description) VALUES (6, '1945');
INSERT INTO options (question_id, description) VALUES (6, '1960');
INSERT INTO options (question_id, description) VALUES (6, '1903');
INSERT INTO options (question_id, description) VALUES (7, 'Option A');
INSERT INTO options (question_id, description) VALUES (7, 'Option B');
INSERT INTO options (question_id, description) VALUES (7, 'Option C');
INSERT INTO options (question_id, description) VALUES (7, 'Option D');
INSERT INTO options (question_id, description) VALUES (8, 'Option A');
INSERT INTO options (question_id, description) VALUES (8, 'Option B');
INSERT INTO options (question_id, description) VALUES (8, 'Option C');
INSERT INTO options (question_id, description) VALUES (8, 'Option D');
INSERT INTO options (question_id, description) VALUES (9, 'Yes');
INSERT INTO options (question_id, description) VALUES (9, 'No');
INSERT INTO options (question_id, description) VALUES (10, 'Yes');
INSERT INTO options (question_id, description) VALUES (10, 'No');
INSERT INTO options (question_id, description) VALUES (11, 'Yes');
INSERT INTO options (question_id, description) VALUES (11, 'No');
