INSERT INTO options (question_id, description) VALUES (1, 'Option A');
INSERT INTO options (question_id, description) VALUES (1, 'Option B');
INSERT INTO options (question_id, description) VALUES (1, 'Option C');
INSERT INTO options (question_id, description) VALUES (1, 'Option D');
INSERT INTO options (question_id, description) VALUES (2, 'Option A');
INSERT INTO options (question_id, description) VALUES (2, 'Option B');
INSERT INTO options (question_id, description) VALUES (2, 'Option C');
INSERT INTO options (question_id, description) VALUES (2, 'Option D');
INSERT INTO options (question_id, description) VALUES (3, 'Option A');
INSERT INTO options (question_id, description) VALUES (3, 'Option B');
INSERT INTO options (question_id, description) VALUES (3, 'Option C');
INSERT INTO options (question_id, description) VALUES (3, 'Option D');
INSERT INTO options (question_id, description) VALUES (4, 'Option A');
INSERT INTO options (question_id, description) VALUES (4, 'Option B');
INSERT INTO options (question_id, description) VALUES (4, 'Option C');
INSERT INTO options (question_id, description) VALUES (4, 'Option D');
INSERT INTO options (question_id, description) VALUES (5, 'Option A');
INSERT INTO options (question_id, description) VALUES (5, 'Option B');
INSERT INTO options (question_id, description) VALUES (5, 'Option C');
INSERT INTO options (question_id, description) VALUES (5, 'Option D');
INSERT INTO options (question_id, description) VALUES (6, 'Option A');
INSERT INTO options (question_id, description) VALUES (6, 'Option B');
INSERT INTO options (question_id, description) VALUES (6, 'Option C');
INSERT INTO options (question_id, description) VALUES (6, 'Option D');
INSERT INTO options (question_id, description) VALUES (7, 'Option A');
INSERT INTO options (question_id, description) VALUES (7, 'Option B');
INSERT INTO options (question_id, description) VALUES (7, 'Option C');
INSERT INTO options (question_id, description) VALUES (7, 'Option D');
INSERT INTO options (question_id, description) VALUES (8, 'Option A');
INSERT INTO options (question_id, description) VALUES (8, 'Option B');
INSERT INTO options (question_id, description) VALUES (8, 'Option C');
INSERT INTO options (question_id, description) VALUES (8, 'Option D');
INSERT INTO options (question_id, description) VALUES (9, 'Yes');
INSERT INTO options (question_id, description) VALUES (9, 'No');
INSERT INTO options (question_id, description) VALUES (10, 'Yes');
INSERT INTO options (question_id, description) VALUES (10, 'No');
INSERT INTO options (question_id, description) VALUES (11, 'Yes');
INSERT INTO options (question_id, description) VALUES (11, 'No');
